#!/bin/bash
#
# Showing the use of rsync to backup a remote home directory, while ignoring a large file
# that is of no use to me and deleting local files that no longer exist on the remote server

# Backup ~HOME_DIR from REMOTE_SERVER incrementally
# Will delete files locally that no longer exist in remote HOME_DIR
# Exclude .btmail -- containts 120MB word list for mail filter
rsync -avzh --exclude '.btmail' --delete REMOTE_USER@REMOTE.SERVER.EDU:~HOME_DIR ~/Documents/WHERE/TO/STORE/LOCAL/BACKUP
